// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const poolInitialized = table("pool_initialized", {
  chainId: db.uint64('chain_id'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  blockTimestamp: db.uint256('block_timestamp'),
  id: db.bytes32('id'),
  currency0: db.address('currency0'),
  currency1: db.address('currency1'),
  fee: db.uint24('fee'),
  tickSpacing: db.int24('tick_spacing'),
  hooks: db.address('hooks'),
  sqrtPriceX96: db.uint160('sqrt_price_x96'),
  tick: db.int24('tick'),
})

export const poolSwap = table("pool_swap", {
  chainId: db.uint64('chain_id'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  blockTimestamp: db.uint256('block_timestamp'),
  id: db.bytes32('id'),
  sender: db.address('sender'),
  amount0: db.int128('amount0'),
  amount1: db.int128('amount1'),
  sqrtPriceX96: db.uint160('sqrt_price_x96'),
  liquidity: db.uint128('liquidity'),
  tick: db.int24('tick'),
  fee: db.uint24('fee'),
})
